### ISSUE TITLE
Add VRT paths to override 404

### ISSUE THREAD

**Issue by gilzow** [platformsh-templates/django3#49]
### What in this template can be improved or added as a feature?

Django includes the URL for the not found page in the output of the page. This causes the VRT tests for 404 to fail as the text content is different. Add an override for that path to remove this false negative.

### What exactly should be updated?

templates-paths.js

### How important is this feature to you?

N/A

**Comment by chadwcarlson** [comment]
This is caused because
- pipenv wasn't being used continuously throughout
- `Debug = True`
